# Generated by Django 2.2.12 on 2020-07-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200710_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiBoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_uid', models.CharField(max_length=10, unique=True, verbose_name='微博用户id')),
                ('access_token', models.CharField(max_length=32, verbose_name='权限令牌')),
                ('user_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'user_wei_bo_profile',
            },
        ),
    ]
